panel_index:
    path:     /
    defaults: { _controller: AppPanelBundle:Default:index }

panel_login:
    path:     /login
    defaults: { _controller: vSymfoUserBundle:Security:login }

panel_login_check:
    path:     /login_check
    defaults: { _controller: vSymfoFOSUserBundle:Security:check }

panel_logout:
    path:     /logout
    defaults: { _controller: vSymfoFOSUserBundle:Security:logout }

vsymfo_exception_login_blocked:
    path:     /login-blocked
    defaults: { _controller: "PanelBundle:Exception:loginBlocked" }

vsymfo_user_bundle:
    resource: "@vSymfoUserBundle/Resources/config/routing.yml"
