services:
    app_panel.main_menu_builder:
        class: App\PanelBundle\Menu\PanelMenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@security.authorization_checker"
            - "@translator"
            - "@request_stack"
            - "@router"

    app_panel.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app_panel.main_menu_builder", createMenu]
        tags:
            - { name: knp_menu.menu, alias: panel_main }
