imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
        global_seo_sitename: "%seo_sitename%"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'PanelBundle::form-bootstrap.html.twig'
    exception_controller: "vsymfo_core.twig.exception_controller:showAction"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    node: /usr/bin/node
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        uglifyjs2:
            bin: /usr/bin/uglifyjs
        uglifycss:
            bin: /usr/bin/uglifycss

# BraincraftedBootstrapBundle
braincrafted_bootstrap:
    auto_configure:
        assetic: false
        twig: false
        knp_menu: false
        knp_paginator: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            StofDoctrineExtensionsBundle: ~
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            CCDNUserSecurityBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                alias: ~
                prefix: CCDNUser\SecurityBundle\Entity
                is_bundle: true

# StofDoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true # ta opcja powoduje, że jeżeli encja nie ma tłumaczenia to użyty będzie język domyślny
    orm:
        default:
            sluggable: true
            sortable: true
            timestampable: true
            blameable: true
            softdeleteable: true
            translatable: false
            tree: false
            loggable: false
            uploadable: false

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:      { type: memory }

# Theme Bundle
liip_theme:
    themes: "%app_themes%"
    active_theme: "%app_theme_active%"
    load_controllers: false
    assetic_integration: true
    path_patterns:
        app_resource:
            - "%%app_path%%/../../private/%app_theme_dir%/%%current_theme%%/views/%%template%%"
        bundle_resource_dir:
            - "%%dir%%/../../private/%app_theme_dir%/%%current_theme%%/bundles/%%bundle_name%%/%%override_path%%"

# FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: frontend
    user_class: vSymfo\Bundle\UserBundle\Entity\User
    group:
        group_class: vSymfo\Bundle\UserBundle\Entity\Group
    from_email:
        address: "%email_address_noreply%"
        sender_name: "%seo_sitename%"
    registration:
        confirmation:
            enabled: true

# I18n Routing
jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%locales%"
    strategy: prefix_except_default

# for CCDNUser SecurityBundle
ccdn_user_security:
    entity:
        user:
            class: vSymfo\Bundle\UserBundle\Entity\User # Required
    route_referer:
        enabled: false
    login_shield:
        route_login:
            name:                  fos_user_security_login
            params:                []
        force_account_recovery:    # Specify all routes to block after attempt limit is reached, and account recovery route to force browser redirect.
            enabled:               false
        block_pages:               # Specify all routes to block after attempt limit is reached.
            enabled:               true
            after_attempts:        10
            duration_in_minutes:   30
            routes:
                - fos_user_security_check
                - fos_user_security_logout
                - panel_login_check
                - panel_logout

# KnpPaginatorBundle
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: "PanelBundle::pagination.html.twig"
        sortable: "PanelBundle::sortable_link.html.twig"

# OneupFlysystemBundle
oneup_flysystem:
    adapters: ~
    filesystems: ~

# VichUploaderBundle
vich_uploader:
    db_driver: orm
    storage:   flysystem
    mappings:  ~

# LiipImagineBundle
liip_imagine:
    controller:
        filter_action:         vsymfo_core.liip_imagine.controller:filterAction
        filter_runtime_action: vsymfo_core.liip_imagine.controller:filterRuntimeAction
    resolvers:
       default:
          web_path: ~
    filter_sets:
        -thumb_outbound:
            quality: 75
            default_image: images/blank_image.png
            filters:
                relative_resize: { heighten: 0, widen: 0 }
                thumbnail: { mode: outbound }
        lightbox:
            quality: 75
            default_image: images/blank_image.png
            filters:
                downscale: { max: [1980, 1280] }

# vSymfo Core
vsymfo_core:
    themes: "%app_themes%"
    theme: "%app_theme_active%"
    theme_backend: "%app_theme_backend_active%"
    document:
        sitename: "%seo_sitename%"
        title_default: "%seo_title_default%"
        title_mode: "%seo_title_mode%"
        title_separator: "%seo_title_separator%"
        description: "%seo_description%"
        keywords: "%seo_keywords%"
        resources_cache_lifetime: "%doc_resources_cache_lifetime%"
        resources_loading_timeout: "%doc_resources_loading_timeout%"
        versioning_enable: true
        versioning_version: 1
        meta_viewport: "%doc_meta_viewport%"
        favicon_enable: "%favicon_enable%"
        favicon_tile_color: "%favicon_tile_color%"
        pdf_duration: "%pdf_duration%"
        pdf_wkhtmltopdf_bin: /usr/local/bin/wkhtmltopdf
        cdn_enable: "%cdn_enable%"
        cdn_javascript: "%cdn_javascript%"
        cdn_css: "%cdn_css%"
        cdn_image: "%cdn_image%"
    pagination:
        limit: "%pagination_limit%"
        pages_in_range: "%pagination_pages_in_range%"
    mailer:
        noreply_email: "%email_address_noreply%"
        default_email: "%email_address_default%"
