backend:
    resource: "@AppBackendBundle/Resources/config/routing.yml"
    options:
        theme_group: backend

core_bundle:
    resource: "@AppCoreBundle/Resources/config/routing.yml"

vsymfo_core_bundle:
    resource: "@vSymfoBundleCoreBundle/Resources/config/routing.yml"

# Login block error page.
vsymfo_exception_login_blocked:
    path:     /account/login-blocked
    defaults: { _controller: "AppBackendBundle:Exception:loginBlocked" }

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
