panel:
    resource: "@AppPanelBundle/Resources/config/routing.yml"
    options:
        theme_group: backend

core_bundle:
    resource: "@AppCoreBundle/Resources/config/routing.yml"

vsymfo_core_bundle:
    resource: "@vSymfoBundleCoreBundle/Resources/config/routing.yml"

liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
