security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # panel
        admin_panel:
            switch_user:        true
            pattern:            ^/(((%security_locales%)/%security_admin_panel_dir%)|(%security_admin_panel_dir%))/
            anonymous:          true
            form_login:
                provider:                       fos_userbundle
                csrf_token_generator:           security.csrf.token_manager

                login_path:                     backend_login
                use_forward:                    false
                check_path:                     backend_login_check
                post_only:                      true

                always_use_default_target_path: false
                default_target_path:            backend_homepage
                target_path_parameter:          _target_path
                use_referer:                    true

                failure_path:                   null
                failure_forward:                false
                failure_handler:                ccdn_user_security.component.authentication.handler.login_failure_handler

                username_parameter:             _username
                password_parameter:             _password

                csrf_parameter:                 _csrf_token
            logout:
                path:                           backend_logout
                target:                         backend_homepage

        # front-end
        #frontend:
            #switch_user:        true
            #pattern:            ^/
            #anonymous:          true
            #form_login:
                #provider:                       fos_userbundle
                #csrf_token_generator:           security.csrf.token_manager

                #login_path:                     fos_user_security_login
                #use_forward:                    false
                #check_path:                     fos_user_security_check
                #post_only:                      true

                #always_use_default_target_path: false
                #default_target_path:            frontend_homepage
                #target_path_parameter:          _target_path
                #use_referer:                    true

                #failure_path:                   null
                #failure_forward:                false
                #failure_handler:                ccdn_user_security.component.authentication.handler.login_failure_handler

                #username_parameter:             _username
                #password_parameter:             _password

                #csrf_parameter:                 _csrf_token
            #logout:
                #path:                           fos_user_security_logout
                #target:                         frontend_homepage
            #remember_me:
                #secret:   "%secret%"
                #lifetime: 604800 # 1 week
                #path:     /
                #domain:   ~

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # panel
        - { path: ^/(((%security_locales%)/%security_admin_panel_dir%)|(%security_admin_panel_dir%))/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(((%security_locales%)/%security_admin_panel_dir%)|(%security_admin_panel_dir%))/, role: ROLE_PANEL_ACCESS }
        # front-end
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
